# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tPwh5S7zHR-IWEHOzfLEmNls-2Qm4-ei
"""

print("abc")