# -*- coding: utf-8 -*-
"""SQUARE.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1S70LGN1ZcBa1TlDflA9jPCBCEhfuf8al
"""

n=7
print(n*n)